# Generated by Django 4.2.5 on 2023-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_task_manager_table',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(error_messages={'blank': 'Title is required!!!'}, max_length=200)),
                ('description', models.TextField(error_messages={'blank': 'Description is required!!!'})),
                ('due_date', models.DateField(error_messages={'blank': 'Due Date is required!!!'})),
                ('task_status', models.CharField(choices=[('COMPLETED', 'completed'), ('DELETED', 'deleted'), ('ACTIVE', 'active'), ('OVER DUE', 'over due')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
