# Generated by Django 4.2.5 on 2023-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task_manager_table',
            name='auto_increment_id',
        ),
        migrations.AlterField(
            model_name='user_task_manager_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
