# Generated by Django 4.2.5 on 2023-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app_API', '0002_remove_user_task_manager_table_auto_increment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task_manager_table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_task_manager_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
